# -*- coding: utf-8 -*-
"""1_Mixtral-8x7B-Instruct_Version_1_90.62%.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kIm4kSNku-mXTYnCiVy0ZheSIDQJaOrI

# 1_Mixtral-8x7B-Instruct_Version_1_90.62%
"""

# ----------------------------------------------
# 1. Environment setup and install libraries
# ----------------------------------------------
### Login to Hugging Face ###
!huggingface-cli login

# Check GPU
!nvidia_smi

### 🚀 Step 1: Install Dependencies  ###
!pip install -U transformers==4.51.3 torch==2.6.0+cu124 accelerate bitsandbytes datasets==3.5.0 peft==0.13.0 fsspec==2023.9.0 --extra-index-url https://download.pytorch.org/whl/cu124

### 🔧 Step 2: Set Environment Variables ###
import os
os.environ["WANDB_DISABLED"] = "true"  # Disable Weights & Biases logging
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"  # Dynamic memory allocation

### 🧠 Step 3: Import Libraries ###
import gc
import atexit
import contextlib
import logging
import torch
import subprocess
import time
import re
from contextlib import contextmanager
from typing import List, Dict, Optional, Any
import json
from rich.console import Console
console = Console()

# Transformers & PEFT
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    TrainerCallback,
    pipeline,
    DataCollatorForLanguageModeling
)
from peft import LoraConfig, get_peft_model, PeftModel, PeftConfig

# Datasets and Processing
from datasets import Dataset
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# Visualization and Utilities
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
from openpyxl.styles import Alignment
import pkg_resources

### 📝 Step 4: Logging Configuration ###
logging.basicConfig(format="%(asctime)s - %(levelname)s - %(message)s", level=logging.INFO)

### 📦 Step 5: Dependency Version Check Function ###
def check_dependencies():
    required_versions = {
        'transformers': '4.51.3',
        'torch': '2.6.0',
        'datasets': '3.5.0',
        'peft': '0.13.0',
        'openpyxl': '3.0.0'
    }
    print("🔍 Checking dependency versions...\n")
    for pkg, required in required_versions.items():
        try:
            installed = pkg_resources.get_distribution(pkg).version
            status = "✅ OK" if installed >= required else "⚠️ Too Low"
            print(f"{pkg}: Current version {installed} (Required >= {required}) {status}")
        except Exception as e:
            print(f"{pkg}: Not installed ❌")

check_dependencies()

### ⚙️ Step 6: Check GPU Status ###
print("\n🖥️ CUDA Available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("🧠 GPU Model:", torch.cuda.get_device_name(0))

torch.cuda.empty_cache()

### 🧼 Step 7: Define Resource Manager ###
@contextlib.contextmanager
def manage_resources(model=None):
    try:
        yield
    finally:
        if model is not None:
            del model
        gc.collect()
        torch.cuda.empty_cache()
        logging.info("Resources cleaned (manage_resources)")

@contextlib.contextmanager
def eval_mode(model):
    model.eval()
    try:
        yield
    finally:
        model.train()

### ⏱️ Step 7.5: Define Timer Decorator ###
def timer(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"⏱️ '{func.__name__}' execution time: {end - start:.2f} seconds")
        return result
    return wrapper

### 🧹 Step 8: Program Exit Cleanup ###
def cleanup():
    global model, trainer
    if 'model' in globals():
        del model
    if 'trainer' in globals():
        del trainer
    gc.collect()
    torch.cuda.empty_cache()
    print("✅ Program exited, resources cleaned (atexit)")

atexit.register(cleanup)

# ---------------------------------
# 2. Config Class and Constants
# ---------------------------------
class Config:
    MAX_NEW_TOKENS = 256
    MAX_RETRIES = 2
    RETRY_DELAY = 2
    MAX_ATTEMPTS = 2
    MAX_CRITERIA_RETRIES = 2

    CRITERIA = [
        "Co-reference issues", "Grammatical errors", "Misspellings", "Incomplete sentences",
        "Unsolvable problems", "Unrealistic", "Unit issues", "Topic safety",
        "Not satisfying grade requirement", "Not satisfying section requirement",
        "Trivial", "Not a word problem"
    ]

    HIGH_RISK_CRITERIA = [
        "Unsolvable problems", "Topic safety"
    ]

    BASE_PROMPT_TEMPLATE = '''
    [INST]
    You are a math education evaluator. Your task is to evaluate the following math word problem using 12 binary criteria.
    Analyze the problem carefully and assign 0 or 1 based on the criteria definitions.

    ⚠️ Output format rules:
    - Output EXACTLY 12 lines, one for each criterion listed below.
    - Each line MUST be formatted as: "- Criterion: 0" or "- Criterion: 1".
    - Use ONLY the criterion names provided, in the exact order.
    - DO NOT include explanations, numbered lists, descriptions, or any extra text.
    - DO NOT skip, reorder, or add criteria.
    - Non-compliance (e.g., adding explanations, using incorrect format) will invalidate the output.
    - 0 indicates an error is detected; 1 indicates no error is detected.

    Criteria (do NOT include in output):
    1. Co-reference issues: Unclear pronouns/references (0 if present, 1 if absent).
    2. Grammatical errors: Grammar mistakes (0 if present, 1 if absent).
    3. Misspellings: Spelling errors (0 if present, 1 if absent).
    4. Incomplete sentences: Sentences missing components (0 if present, 1 if absent).
    5. Unsolvable problems: Missing information prevents solving (0 if true, 1 if solvable).
    6. Unrealistic: Implausible scenario (0 if unrealistic, 1 if realistic).
    7. Unit issues: Incorrect/inconsistent units (0 if present, 1 if absent).
    8. Topic safety: Violent/inappropriate content (0 if present, 1 if safe).
    9. Not satisfying grade requirement: Too hard/easy for grade (0 if true, 1 if appropriate).
    10. Not satisfying section requirement: Mismatches section (0 if true, 1 if matches).
    11. Trivial: Too simple for grade (0 if trivial, 1 if non-trivial).
    12. Not a word problem: Equation only, no narrative (0 if true, 1 if narrative).

    Example of CORRECT output:
    - Co-reference issues: 1
    - Grammatical errors: 1
    - Misspellings: 1
    - Incomplete sentences: 1
    - Unsolvable problems: 1
    - Unrealistic: 1
    - Unit issues: 1
    - Topic safety: 1
    - Not satisfying grade requirement: 1
    - Not satisfying section requirement: 1
    - Trivial: 0
    - Not a word problem: 1

    Example of INCORRECT output (DO NOT DO THIS):
    - 1. Co-reference issues: 1 (no pronouns)
    - Grammatical errors: 1 (correct grammar)
    - Missing criterion
    Explanation: This is wrong.

    Grade: {grade}
    Question Type: {question_type}
    Problem: {problem}
    [/INST]
    '''

    ONE_SHOT_EXAMPLE = """Grade: 2
Question Type: Addition
Problem: There are 8 dogs in the park. 3 more dogs come to the park. How many dogs are there now?
- Co-reference issues: 1
- Grammatical errors: 0
- Misspellings: 0
- Incomplete sentences: 1
- Unsolvable problems: 1
- Unrealistic: 1
- Unit issues: 1
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 1
- Not a word problem: 1"""

    THREE_SHOT_EXAMPLE = """Grade: 3
Question Type: Subtraction
Problem: If Jack has 27 apples and he gives 14 apples to his friend, how many apples does Jack have left?
- Co-reference issues: 1
- Grammatical errors: 1
- Misspellings: 1
- Incomplete sentences: 1
- Unsolvable problems: 1
- Unrealistic: 1
- Unit issues: 1
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 1
- Not a word problem: 1

Grade: 4
Question Type: Subtraction
Problem: There are 20 balloons in the box. Some of the balloons popped. If there are now 12 balloons left in the box, how many balloons popped?
- Co-reference issues: 1
- Grammatical errors: 1
- Misspellings: 1
- Incomplete sentences: 1
- Unsolvable problems: 1
- Unrealistic: 1
- Unit issues: 1
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 1
- Not a word problem: 1

Grade: 6
Question Type: Multiplication
Problem: A rectangular garden has a length of 18 meters and a width of 8 meters. What is the area of the garden in square meters?
- Co-reference issues: 1
- Grammatical errors: 1
- Misspellings: 1
- Incomplete sentences: 1
- Unsolvable problems: 1
- Unrealistic: 1
- Unit issues: 1
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 1
- Not a word problem: 1"""

    TEST_CASES = [
        {"grade": "2", "question_type": "Addition", "problem": "How much is 5 plus 3?"},
        {"grade": "2", "question_type": "Addition", "problem": "There is 8 dogs in the park. 3 more dogs come to the park. How many dogs are there now?"},
        {"grade": "3", "question_type": "Addition", "problem": "John has 2 pencils that are 4 inches long each. If he buys another pencil that is 5 inches long, how gram long are all his pencils in total?"},
        {"grade": "1", "question_type": "Addition", "problem": "There are 3 red flowrs and 4 yello flowrs in a vase. How many flowrs are there in total?"},
        {"grade": "4", "question_type": "Subtraction", "problem": "There are 20 balloons in the box. Some of the balloons popped. If there are now 12 balloons left in the box, how many balloons popped?"},
        {"grade": "2", "question_type": "Addition", "problem": "There are 7 marbles in a bag and David puts. Now there are 10 in total. How many marbles did David add?"},
        {"grade": "5", "question_type": "Subtraction", "problem": "White is 19 years old and Black is 7 years younger than white. How old is Kalu?"},
        {"grade": "3", "question_type": "Subtraction", "problem": "If Jack has 27 apples and he gives 14 apples to his friend, how many apples does Jack have left?"},
        {"grade": "6", "question_type": "Multiplication", "problem": "A rectangular swimming pool has a length of 15 meters and a width of 6 meters. What is the area of the swimming pool in square meters?"},
        {"grade": "4", "question_type": "Addition", "problem": "A Murderer killed 5 persons last January. The murderer killed 4 persons in February. How many persons were killed at the end of the February month?"},
        {"grade": "6", "question_type": "Multiplication", "problem": "A rectangular garden has a length of 18 meters and a width of 8 meters. What is the area of the garden in square meters?"},
        {"grade": "3", "question_type": "Addition", "problem": "An man has a 14 number of eyes. If it blinks 5 of them, how many eyes are still open?"},
        {"grade": "2", "question_type": "Addition", "problem": "A bag contains 10 marbles. If you remove 2 marbles and add some more, how many marbles are in the bag now?"},
        {"grade": "2", "question_type": "Addition", "problem": "234+567"},
        {"grade": "3", "question_type": "Subtraction", "problem": "Sara killed catched 34 rats and killed 5 rats from them. how many rats are left?"},
        {"grade": "2", "question_type": "Division", "problem": "I have 35 apples and I share them equally with 7 friends. If each friend get 5 apples how many friends are there?"}
    ]

# -----------------------
# 3. Output Definition
# -----------------------

# Define Output Printer
class OutputPrinter:
    def __init__(self):
        self.console = Console()

    def print_case_details(self, case: Dict[str, str], attempt: int, output: str, output_type: str) -> None:
        self.console.print(f"[bold yellow]Math Word Problem:[/bold yellow] {case['problem']}")
        self.console.print(f"[bold yellow]Grade:[/bold yellow] {case['grade']}")
        self.console.print(f"[bold yellow]Question Type:[/bold yellow] {case['question_type']}")
        self.console.print(f"[bold yellow]Attempt:[/bold yellow] {attempt}")
        self.console.print(f"[bold yellow]Model {output_type} Output:[/bold yellow]\n{output}")
        self.console.print(f"[dim]{'-'*50}[/dim]")


# Define Output Formatter
class EnhancedOutputFormatter:
    def __init__(self):
        self.criteria = Config.CRITERIA
        self.norm_map = {
            re.sub(r'[^a-z]', '', c.lower()): c
            for c in Config.CRITERIA
        }

    def parse_line(self, line: str) -> tuple:
        line = line.strip()
        match = re.match(r'^[-\*]?\s*([^:]+?)\s*:\s*([0-1])', line)
        return (self.norm_map.get(re.sub(r'[^a-z]', '', match.group(1).lower()), None),
                match.group(2)) if match else (None, None)

    def process(self, raw_output: str) -> tuple:
        output_map = {}
        missing_flags = {c: True for c in self.criteria}

        for line in raw_output.split('\n'):
            criterion, value = self.parse_line(line)
            if criterion and value in ('0', '1'):
                output_map[criterion] = value
                missing_flags[criterion] = False

        formatted = [f"- {c}: {output_map.get(c, 'N/A')}" for c in self.criteria]
        return '\n'.join(formatted), raw_output, missing_flags

# --------------------------------------
# 4. Safe Processor with Manual Review
# --------------------------------------
class SafeProcessor:
    def __init__(self, model, tokenizer):
        self.pipe = pipeline(
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            device_map={"": "cuda:0"}
        )
        self.formatter = EnhancedOutputFormatter()
        self.console = OutputPrinter()

    def _log_review_case(self, case: dict, raw: str):
        log_entry = f"""
        [REVIEW REQUIRED] {time.ctime()}
        Problem: {case['problem'][:50]}...
        Grade: {case['grade']}
        Missing Criteria: {', '.join([c for c in Config.HIGH_RISK_CRITERIA if c not in raw]) or 'None'}
        Raw Output: {raw[:200]}... (truncated)
        """
        with open("review_cases.log", "a") as f:
            f.write(log_entry + "-"*50 + "\n")

    def process_case(self, case: dict, template: str) -> dict:
        for attempt in range(Config.MAX_RETRIES):
            try:
                prompt = template.format(**case)
                raw_output = self.pipe(
                    prompt,
                    max_new_tokens=Config.MAX_NEW_TOKENS,
                    do_sample=False,
                    return_full_text=False
                )[0]['generated_text']

                self.console.print_case_details(case, attempt + 1, raw_output, "Raw")

                formatted, raw, missing = self.formatter.process(raw_output)

                self.console.print_case_details(case, attempt + 1, formatted, "Formatted")

                if any(missing[c] for c in Config.HIGH_RISK_CRITERIA):
                    self._log_review_case(case, raw_output)

                return {
                    "formatted": formatted,
                    "raw": raw,
                    "missing": missing
                }

            except Exception as e:
                logging.error(f"Attempt {attempt+1} failed: {str(e)}")
                torch.cuda.empty_cache()

        return {
            "formatted": None,
            "raw": "Generation failed",
            "missing": {c: True for c in Config.CRITERIA}
        }

    def process_batch(self, cases: List[Dict[str, str]], template: str) -> List[Dict]:
        outputs = []
        for case in cases:
            output = self.process_case(case, template)
            outputs.append(output)
        return outputs

# -------------------------------
# 5. Model Loading Function
# -------------------------------
def load_model_and_tokenizer() -> tuple:
    """Load the quantized model and tokenizer"""
    model_name = "mistralai/Mixtral-8x7B-Instruct-v0.1"

    # Quantization Configuration
    quant_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True
    )

    # Load the model
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=quant_config,
        torch_dtype=torch.bfloat16,
        trust_remote_code=True,
        device_map={"": "cuda:0"},
        low_cpu_mem_usage=True,
        max_memory={0: "24GiB"},
        resume_download=True
    )
    model.config.use_cache = False

    # Load the tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name, padding_side="right")
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Print the GPU info
    print("GPU memory allocated after loading quantized model:",
          torch.cuda.memory_allocated(0) / 1024**3, "GB")
    print("GPU memory reserved after loading quantized model:",
          torch.cuda.memory_reserved(0) / 1024**3, "GB")

    return model, tokenizer

# -------------------------------
# 6. Prompt Template Utilities
# -------------------------------
def make_template(base_template: str, example: Optional[str] = None) -> str:
    if not example:
        return base_template
    plural = "s" if '\n' in example else ""
    return base_template.replace(
        "[INST]",
        f"[INST]\nUse the following example{plural} to guide your scoring:\n{example}\n"
    )

# -------------------------------
# 7. Results Saving
# -------------------------------
def save_enhanced_results(results: List[dict], filename: str):
    expanded_data = []
    for res in results:
        case = res["case"]
        result = res["result"]

        row = {
            "Problem": case["problem"],
            "Grade": case["grade"],
            "QuestionType": case["question_type"],
            "RawOutput": result["raw"]
        }

        for criterion in Config.CRITERIA:
            row[criterion] = result["formatted"].split('\n')[Config.CRITERIA.index(criterion)].split(": ")[1]
            row[f"{criterion}_missing"] = "Yes" if result["missing"][criterion] else "No"

        expanded_data.append(row)

    pd.DataFrame(expanded_data).to_excel(filename, index=False, engine='openpyxl')
    print(f"✅ Results saved to {filename}")

# ----------------------------------------------------
# 8. Compare Prompting result with human evaluation
# ----------------------------------------------------
def compare_prompting_results(model_eval_file: str, output_prefix: str) -> float:
    """Compare the accuracy of different prompting methods with human evaluation"""
    console = Console()

    df_human = pd.read_excel("MWP evaluation sheet.xlsx")

    df_model = pd.read_excel(model_eval_file)

    if 'Section' in df_human.columns and 'Question Type' not in df_human.columns:
        df_human.rename(columns={'Section': 'Question Type'}, inplace=True)

    # Clean the Problem field (remove spaces + convert to lowercase)
    df_human['Problem'] = df_human['Problem'].str.strip().str.lower()
    df_model['Problem'] = df_model['Problem'].str.strip().str.lower()

    # Merge datasets (left join to retain all human-evaluated problems)
    df_merged = pd.merge(
        df_human,
        df_model,
        on='Problem',
        how='left',
        suffixes=('_human', '_model')
    )

    # Dynamically determine common criteria
    common_criteria = [
        col for col in Config.CRITERIA
        if col in df_human.columns and col in df_model.columns
    ]

    # Calculate accuracy rate
    total_correct = 0
    total_comparisons = 0
    problem_accuracy = []

    for idx, row in df_merged.iterrows():
        correct_count = 0
        for col in common_criteria:
            human_val = str(row[f"{col}_human"]).strip()
            model_val = str(row.get(f"{col}_model", "N/A")).strip()

            if human_val == model_val:
                correct_count += 1

        accuracy = (correct_count / len(common_criteria)) * 100 if common_criteria else 0
        problem_accuracy.append({
            'Problem': row['Problem'],
            'Accuracy': accuracy,
            'Correct_Count': correct_count,
            'Total_Columns': len(common_criteria)
        })
        total_correct += correct_count
        total_comparisons += len(common_criteria)

    # Calculate overall accuracy rate
    overall_accuracy = (total_correct / total_comparisons) * 100 if total_comparisons > 0 else 0

    # Save results
    accuracy_df = pd.DataFrame(problem_accuracy)
    accuracy_output = f"accuracy_results_{output_prefix}.xlsx"
    accuracy_df.to_excel(accuracy_output, index=False)
    console.print(f"[bold green]Saved {accuracy_output}[/bold green]")

    return overall_accuracy

# -------------------------------
# 9. I/O Utilities
# -------------------------------
def parse_output_to_dict(output: Optional[str], criteria: List[str]) -> Dict[str, str]:
    result = {criterion: 'N/A' for criterion in criteria}
    if output is None:
        return result
    for line in output.strip().split('\n'):
        try:
            criterion, value = line.split(':', 1)
            criterion = criterion.replace('- ', '').strip()
            value = value.strip()
            if criterion in criteria and value in ('0', '1', 'N/A'):
                result[criterion] = value
        except (ValueError, IndexError):
            continue
    return result

# -------------------------------
# 10. Merge Outputs Utilities
# -------------------------------
def make_row(
    case: Dict[str, str],
    zero: Dict[str, str],
    one: Dict[str, str],
    three: Dict[str, str],
    criteria: List[str]
) -> Dict[str, str]:
    row = {
        'Problem': case['problem'],
        'Grade': case['grade'],
        'Question Type': case['question_type']
    }
    for c in criteria:
        row[f'Zero-Shot_{c}'] = zero[c]
        row[f'One-Shot_{c}'] = one[c]
        row[f'Three-Shot_{c}'] = three[c]
    return row


# Merge Outputs definition
def merge_outputs(
    test_cases: List[Dict[str, str]],
    zero_shot_outputs: List[Dict],
    one_shot_outputs: List[Dict],
    three_shot_outputs: List[Dict],
    criteria: List[str],
    output_file: str = "all_prompt_outputs.xlsx"
) -> None:
    console = Console()
    console.print("[bold green]Merging outputs into a single dataset and saving to Excel...[/bold green]")

    data = []
    for idx, case in enumerate(test_cases):
        zero = parse_output_to_dict(zero_shot_outputs[idx]["formatted"], criteria)
        one = parse_output_to_dict(one_shot_outputs[idx]["formatted"], criteria)
        three = parse_output_to_dict(three_shot_outputs[idx]["formatted"], criteria)
        data.append(make_row(case, zero, one, three, criteria))

    try:
        pd.DataFrame(data).to_excel(output_file, index=False, engine='openpyxl')
        console.print(f"[bold green]Merged outputs saved to {output_file}[/bold green]")
    except Exception as e:
        logging.error(f"Failed to save Excel file: {e}")
        console.print(f"[bold red]Error saving Excel file: {e}[/bold red]")

# ----------------------------------
# 11. Data Handling and processing
# ----------------------------------
# Dataset Validation
def validate_dataset(df, required_columns, critical_columns=['Problem']):
    missing_critical = [col for col in critical_columns if col not in df.columns]
    if missing_critical:
        raise ValueError(f"❌ Missing critical columns: {missing_critical}")
    missing_non_critical = [col for col in required_columns if col not in df.columns and col not in critical_columns]
    if missing_non_critical:
        logging.warning(f"⚠️ Dataset missing non-critical columns: {missing_non_critical}")
    check_columns = [col for col in ['Problem', 'Grade', 'Question Type'] if col in df.columns]
    if check_columns:
        df = df.dropna(subset=check_columns)
    return df


# Dataset Handling
def load_and_validate_dataset():
    """Load and validate the dataset."""
    error_columns = Config.CRITERIA
    df_final = pd.read_csv('df_final.csv', encoding='ISO-8859-1')
    df_final = validate_dataset(df_final, ['Problem', 'Grade', 'Section'] + error_columns)
    return df_final

def split_dataset(df_final):
    """Split dataset into training, validation, and test sets."""
    random_seed = 42
    df_train, temp_data = train_test_split(
        df_final,
        test_size=0.2,
        stratify=df_final["Grade"],
        random_state=random_seed
    )
    df_val, df_test = train_test_split(
        temp_data,
        test_size=0.5,
        stratify=temp_data["Grade"],
        random_state=random_seed
    )

    train_dataset = Dataset.from_pandas(df_train)
    val_dataset = Dataset.from_pandas(df_val)
    test_dataset = Dataset.from_pandas(df_test)

    print(f"Total samples: {len(df_final)}")
    print(f"Training set: {len(df_train)} ({len(df_train)/len(df_final)*100:.2f}%)")
    print(f"Validation set: {len(df_val)} ({len(df_val)/len(df_final)*100:.2f}%)")
    print(f"Test set: {len(df_test)} ({len(df_test)/len(df_final)*100:.2f}%)")

    return train_dataset, val_dataset, test_dataset

def format_and_tokenize_datasets(train_dataset, val_dataset, tokenizer):
    """Format and tokenize datasets."""
    def format_data(examples):
        prompts = []
        labels = []
        error_columns = Config.CRITERIA
        for i in range(len(examples["Problem"])):
            prompt = (
                f"[INST]Analyze this math problem and output 12 lines, each in the format '- Criterion: 0' or '- Criterion: 1' for these error types: {', '.join(error_columns)}.\n"
                f"0 indicates an error is detected; 1 indicates no error is detected.\n"
                f"Problem: {examples['Problem'][i]}\n"
                f"Grade: {examples['Grade'][i]}\n"
                f"Section: {examples['Section'][i]}\n"
                "Output:\n[/INST]"
            )
            # label_lines = [f"- {col}: {str(examples.get(col, 'N/A')[i])}" for col in error_columns]
            label_lines = [f"- {col}: {str(examples.get(col, 'N/A')[i])}" for col in error_columns]
            label = '\n'.join(label_lines)
            prompts.append(prompt)
            labels.append(label)
        return {"prompt": prompts, "label": labels}
    # Define tokenize function
    def tokenize_function(examples):
        tokenizer.padding_side = "right"
        full_texts = [p + '\n' + l for p, l in zip(examples["prompt"], examples["label"])]
        tokenized = tokenizer(
            full_texts,
            padding="max_length",
            truncation=True,
            max_length=256,
            return_tensors="pt"
        )
        input_ids = tokenized["input_ids"]
        attention_mask = tokenized["attention_mask"]

        prompt_tokenized = tokenizer(
            examples["prompt"],
            padding="max_length",
            truncation=True,
            max_length=256 - 48,
            return_tensors="pt"
        )
        labels = torch.full_like(input_ids, -100, dtype=torch.long)

        for i in range(len(examples["prompt"])):
            prompt_len = (prompt_tokenized["attention_mask"][i] == 1).sum().item()
            label_tokens = tokenizer(examples["label"][i], add_special_tokens=False)["input_ids"]
            if prompt_len + len(label_tokens) <= 256:
                labels[i, prompt_len:prompt_len + len(label_tokens)] = torch.tensor(label_tokens, dtype=torch.long)

        return {
            "input_ids": input_ids.tolist(),
            "attention_mask": attention_mask.tolist(),
            "labels": labels.tolist()
        }

    formatted_train_ds = train_dataset.map(format_data, batched=True, remove_columns=train_dataset.column_names)
    tokenized_train = formatted_train_ds.map(tokenize_function, batched=True, remove_columns=["prompt", "label"])
    formatted_val_ds = val_dataset.map(format_data, batched=True, remove_columns=val_dataset.column_names)
    tokenized_val = formatted_val_ds.map(tokenize_function, batched=True, remove_columns=["prompt", "label"])

    print("Training dataset size:", len(tokenized_train))
    print("Validation dataset size:", len(tokenized_val))

    return tokenized_train, tokenized_val

# -------------------------------
# 12. Fine-tuned Model
# -------------------------------
def fine_tune_model(model, tokenizer, tokenized_train, tokenized_val):
    """Fine-tune the model with LoRA configuration."""
    lora_config = LoraConfig(
        r=8,
        lora_alpha=32,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM"
    )

    model = get_peft_model(model, lora_config)
    model.config.use_cache = False
    model.train()

    for name, param in model.named_parameters():
        if "lora" in name:
            param.requires_grad_(True)
        else:
            param.requires_grad_(False)
    print(f"Trainable parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad)}")

    data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

    training_args = TrainingArguments(
        output_dir="./results",
        num_train_epochs=1,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        optim="adamw_8bit",
        learning_rate=2e-5,
        warmup_steps=500,
        bf16=True,
        save_steps=500,
        logging_steps=10,
        eval_strategy="steps",
        eval_steps=100,
        save_total_limit=5,
        load_best_model_at_end=True,
        metric_for_best_model="loss",
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train,
        eval_dataset=tokenized_val,
        data_collator=data_collator,
    )

    trainer.train()

    adapter_path = "./fine_tuned_mixtral-8x7b-instruct"
    os.makedirs(adapter_path, exist_ok=True)

    model.save_pretrained(adapter_path)
    tokenizer.save_pretrained(adapter_path)

    print("Files in adapter_path:", os.listdir(adapter_path))
    print(f"Model saved: {adapter_path}")

    # return model, tokenizer
    return model, tokenizer, trainer


# Training Loss Visualization
def visualize_training_loss(trainer):
    """Visualize training and validation loss."""
    log_history = trainer.state.log_history
    train_loss = [log['loss'] for log in log_history if 'loss' in log]
    val_loss = [log['eval_loss'] for log in log_history if 'eval_loss' in log]
    train_steps = [log['step'] for log in log_history if 'loss' in log]
    val_steps = [log['step'] for log in log_history if 'eval_loss' in log]

    if len(train_steps) > len(train_loss):
        train_steps = train_steps[:len(train_loss)]

    plt.figure(figsize=(12, 6), dpi=300)
    plt.plot(train_steps, train_loss, label='Training Loss')
    plt.plot(val_steps, val_loss, label='Validation Loss')
    plt.xlabel('Step')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    plt.show()

# -------------------------------
# 13. Test Fine-Tuned Model
# -------------------------------
def test_fine_tuned_model(model, tokenizer):
    print("=== Testing Fine-Tuned Model ===")

    # Switch model to evaluation mode
    print("Switching model to evaluation mode...")
    model.eval()

    # Ensure tokenizer is configured correctly
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Create SafeProcessor instance
    processor = SafeProcessor(model, tokenizer)

    # Process test cases
    console.print("[bold green]Processing test cases...[/bold green]")
    outputs = processor.process_batch(Config.TEST_CASES, Config.BASE_PROMPT_TEMPLATE)

    # Save results to Excel
    results = [
        {"case": case, "result": output}
        for case, output in zip(Config.TEST_CASES, outputs)
    ]
    save_enhanced_results(results, "df_evaluation_fine_tuned.xlsx")

# -------------------------------------------
# 14. Compare Results - Fine-tuned VS Human
# -------------------------------------------
def compare_results():
    # Load human evaluation results
    df_human_evaluation = pd.read_excel("MWP evaluation sheet.xlsx")

    # Rename "Section" to "Question Type" if needed
    if 'Section' in df_human_evaluation.columns and 'Question Type' not in df_human_evaluation.columns:
        df_human_evaluation.rename(columns={'Section': 'Question Type'}, inplace=True)

    # Load fine-tuned model evaluation results
    df_evaluation_fine_tuned = pd.read_excel("df_evaluation_fine_tuned.xlsx")

    # Dynamically determine common criteria
    human_columns = set(df_human_evaluation.columns)
    ft_columns = set(df_evaluation_fine_tuned.columns)
    common_criteria = [col for col in Config.CRITERIA if col in human_columns and col in ft_columns]
    console.print(f"[bold green]Common criteria: {common_criteria}[/bold green]")

    # Validate datasets using common criteria
    df_human_evaluation = validate_dataset(df_human_evaluation, ['Problem'] + common_criteria)
    df_evaluation_fine_tuned = validate_dataset(df_evaluation_fine_tuned, ['Problem'] + common_criteria + ['RawOutput'])

    # Data preprocessing: Clean Problem column
    df_human_evaluation['Problem'] = df_human_evaluation['Problem'].str.strip()
    df_evaluation_fine_tuned['Problem'] = df_evaluation_fine_tuned['Problem'].str.strip()

    # Merge datasets
    df_merged = pd.merge(
        df_human_evaluation,
        df_evaluation_fine_tuned,
        on='Problem',
        how='inner',
        suffixes=('_human', '_ft'))
    console.print(f"[bold green]Merged dataset contains {len(df_merged)} problems[/bold green]")

    # Verify columns to compare
    columns_to_compare = common_criteria
    available_columns = [col for col in columns_to_compare
                        if f"{col}_human" in df_merged.columns and f"{col}_ft" in df_merged.columns]
    console.print(f"[bold green]Comparable criteria: {available_columns}[/bold green]")

    # Calculate per-problem accuracy and discrepancies
    problem_accuracy = []
    total_correct = 0
    total_comparisons = 0
    discrepancies = []
    na_counts = {col: 0 for col in available_columns}

    for idx, row in df_merged.iterrows():
        correct_count = 0
        for col in available_columns:
            human_val = row[f"{col}_human"]
            ft_val = row[f"{col}_ft"]
            # Check if RawOutput_ft exists
            raw_model_output = row.get('RawOutput_ft', 'N/A')

            # Handle N/A and null values
            if pd.isna(human_val) or human_val == 'N/A':
                human_val = 'N/A'
            if ft_val == 'N/A':
                na_counts[col] += 1
                discrepancies.append({
                    'Problem': row['Problem'],
                    'Column': col,
                    'Raw_Human': row[f"{col}_human"],
                    'Raw_Model': raw_model_output,
                    'Human': human_val,
                    'Model': 'N/A'
                })
                continue
            if pd.isna(ft_val):
                ft_val = 'N/A'
                na_counts[col] += 1
                discrepancies.append({
                    'Problem': row['Problem'],
                    'Column': col,
                    'Raw_Human': row[f"{col}_human"],
                    'Raw_Model': raw_model_output,
                    'Human': human_val,
                    'Model': 'N/A'
                })
                continue

            # Compare values
            try:
                human_val = str(human_val)
                ft_val = str(ft_val)
                if human_val == ft_val:
                    correct_count += 1
                else:
                    discrepancies.append({
                        'Problem': row['Problem'],
                        'Column': col,
                        'Raw_Human': row[f"{col}_human"],
                        'Raw_Model': raw_model_output,
                        'Human': human_val,
                        'Model': ft_val
                    })
            except Exception as e:
                logging.error(f"Error comparing {col} for problem '{row['Problem'][:30]}': {str(e)}")

        accuracy = (correct_count / len(available_columns)) * 100 if available_columns else 0
        problem_accuracy.append({
            'Problem': row['Problem'],
            'Accuracy': accuracy,
            'Correct_Count': correct_count,
            'Total_Columns': len(available_columns)
        })
        total_correct += correct_count
        total_comparisons += len(available_columns)

    # Calculate overall accuracy
    overall_accuracy = (total_correct / total_comparisons) * 100 if total_comparisons > 0 else 0

    # Create accuracy DataFrame
    problem_accuracy_df = pd.DataFrame(problem_accuracy)
    overall_row = pd.DataFrame([{
        'Problem': 'Overall Accuracy',
        'Total_Columns': total_comparisons,
        'Correct_Count': total_correct,
        'Accuracy': overall_accuracy,
    }])
    problem_accuracy_df = pd.concat([problem_accuracy_df, overall_row], ignore_index=True)
    problem_accuracy_df['Accuracy'] = problem_accuracy_df['Accuracy'].map('{:.3f}'.format)

    # Save accuracy results
    accuracy_output_file = "accuracy_results_fine_tuned.xlsx"
    with pd.ExcelWriter(accuracy_output_file, engine='openpyxl') as writer:
        problem_accuracy_df.to_excel(writer, sheet_name='Accuracy', index=False)
        workbook = writer.book
        worksheet = writer.sheets['Accuracy']
        for cell in worksheet['A'][1:]:
            cell.alignment = Alignment(horizontal='left')
        worksheet.column_dimensions['A'].width = 50
        worksheet.column_dimensions['B'].width = 15
        worksheet.column_dimensions['C'].width = 15
        worksheet.column_dimensions['D'].width = 15
    console.print(f"[bold yellow]Accuracy results saved to {accuracy_output_file}[/bold yellow]")

    # Save discrepancy results
    df_discrepancies = pd.DataFrame(discrepancies)
    console.print(f"[bold yellow]Found {len(df_discrepancies)} discrepancies (including N/A)[/bold yellow]")
    discrepancy_output_file = "discrepancies_fine_tuned.xlsx"
    df_discrepancies.to_excel(discrepancy_output_file, index=False)
    console.print(f"[bold yellow]Discrepancies saved to {discrepancy_output_file}[/bold yellow]")

    # Count discrepancies and N/A frequencies
    discrepancy_counts = df_discrepancies[df_discrepancies['Model'] != 'N/A']['Column'].value_counts().to_dict()
    console.print("\n[yellow]Discrepancy frequency by criterion (excluding N/A):[/yellow]")
    print(discrepancy_counts)
    console.print("\n[yellow]N/A frequency by criterion:[/yellow]")
    print(na_counts)

    # Sample verification: 10% of discrepancies/N/A
    if len(df_discrepancies) > 0:
        sample_size = max(1, len(df_discrepancies) // 10)
        df_sample = df_discrepancies.sample(n=sample_size, random_state=42)
        console.print(f"\n[yellow]Sampling {sample_size} discrepancy/N/A records for verification:[/yellow]")
        for _, row in df_sample.iterrows():
            console.print(
                f"Problem: {row['Problem'][:30]}...\n"
                f"Column: {row['Column']}\n"
                f"Raw Human: {row['Raw_Human']}\n"
                f"Raw Model: {row['Raw_Model'][:50]}...\n"
                f"Formatted Human: {row['Human']}\n"
                f"Formatted Model: {row['Model']}"
            )

    # Print accuracy summary
    console.print(f"\n[bold yellow]Total problems: {len(df_merged)}[/bold yellow]")
    console.print(f"[bold yellow]Overall accuracy: {overall_accuracy:.3f}%[/bold yellow]")
    console.print("\n[bold yellow]Per-problem accuracy:[/bold yellow]")
    print(problem_accuracy_df)

    return problem_accuracy_df, df_discrepancies

# ------------
# Check GPU
# ------------
def check_gpu_status():
    """Check GPU and CUDA environment information."""
    print("Checking GPU and CUDA environment information...")
    print(f"PyTorch version: {torch.__version__}")
    if torch.cuda.is_available():
        print(f"Current GPU device index: {torch.cuda.current_device()}")
        print(f"GPU model: {torch.cuda.get_device_name(0)}")
        print(f"Total GPU memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.2f} GB")
        print(f"Final GPU memory allocated: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
    else:
        print("No GPU detected, using CPU.")

# -------------------------------
# 15. Main Execution
# -------------------------------

if __name__ == "__main__":
    try:
        # 1: Load model and tokenizer
        printer = OutputPrinter()  # Initialize printer for console printing
        printer.console.print("[yellow]=============== Load model and tokenizer ===============[/yellow]")
        model, tokenizer = load_model_and_tokenizer()

        # 2. Initialize other components
        processor = SafeProcessor(model, tokenizer)

        # 3. Create prompt templates
        one_shot_template = make_template(Config.BASE_PROMPT_TEMPLATE, Config.ONE_SHOT_EXAMPLE)
        three_shot_template = make_template(Config.BASE_PROMPT_TEMPLATE, Config.THREE_SHOT_EXAMPLE)

        # 4. Run prompting
        printer.console.print("[yellow]=============== Run prompting ===============[/yellow]")
        start_total_prompting = time.time()

        # Zero-Shot Prompting
        printer.console.print("[bold green]=============== Zero-Shot Prompting ===============[/bold green]")
        zero_start = time.time()
        zero_outputs = processor.process_batch(Config.TEST_CASES, Config.BASE_PROMPT_TEMPLATE)
        zero_time = time.time() - zero_start

        save_enhanced_results([{"case": case, "result": output} for case, output in zip(Config.TEST_CASES, zero_outputs)], "zero_shot_outputs.xlsx")
        zero_accuracy = compare_prompting_results("zero_shot_outputs.xlsx", "zero_shot")

        # One-Shot Prompting
        printer.console.print("[bold green]=============== One-Shot Prompting ===============[/bold green]")
        one_start = time.time()
        one_outputs = processor.process_batch(Config.TEST_CASES, one_shot_template)
        one_time = time.time() - one_start

        save_enhanced_results([{"case": case, "result": output} for case, output in zip(Config.TEST_CASES, one_outputs)], "one_shot_outputs.xlsx")
        one_accuracy = compare_prompting_results("one_shot_outputs.xlsx", "one_shot")

        # Three-Shot Prompting
        printer.console.print("[bold green]=============== Three-Shot Prompting ===============[/bold green]")
        three_start = time.time()
        three_outputs = processor.process_batch(Config.TEST_CASES, three_shot_template)
        three_time = time.time() - three_start

        save_enhanced_results([{"case": case, "result": output} for case, output in zip(Config.TEST_CASES, three_outputs)], "three_shot_outputs.xlsx")
        three_accuracy = compare_prompting_results("three_shot_outputs.xlsx", "three_shot")

        # Calculate overall time
        total_prompting_time = time.time() - start_total_prompting

        # Print results
        printer.console.print(f"""
        [bold cyan]Prompting Execution Times:[/bold cyan]
        - Zero-Shot: {zero_time:.2f} seconds
        - One-Shot: {one_time:.2f} seconds
        - Three-Shot: {three_time:.2f} seconds
        - Total: {total_prompting_time:.2f} seconds
        """)

        printer.console.print(f"""
        [bold green]Prompting Accuracy Results:[/bold green]
        - Zero-Shot: {zero_accuracy:.2f}%
        - One-Shot: {one_accuracy:.2f}%
        - Three-Shot: {three_accuracy:.2f}%
        """)

        # 5. Load and preprocess dataset
        printer.console.print("[yellow]===============  Load and preprocess dataset ===============[/yellow]")
        df_final = load_and_validate_dataset()
        train_dataset, val_dataset, test_dataset = split_dataset(df_final)
        tokenized_train, tokenized_val = format_and_tokenize_datasets(train_dataset, val_dataset, tokenizer)

        # 6. Fine-tune model
        printer.console.print("[yellow]===============  Fine-tune model ===============[/yellow]")
        start_training = time.time()
        fine_tuned_model, fine_tuned_tokenizer, trainer = fine_tune_model(model, tokenizer, tokenized_train, tokenized_val)
        total_training_time = time.time() - start_training
        printer.console.print(f"\n[bold cyan]Total Training Time: {total_training_time/60:.2f} minutes[/bold cyan]")

        # 7. Visualize training loss
        printer.console.print("[yellow]===============  Visualize training loss ===============[/yellow]")
        visualize_training_loss(trainer)

        # 8. Test fine-tuned model
        printer.console.print("[yellow]===============  Test fine-tuned model ===============[/yellow]")
        with manage_resources(model):
            test_fine_tuned_model(fine_tuned_model, fine_tuned_tokenizer)

        # 9. Compare results
        printer.console.print("[yellow]===============  Compare results ===============[/yellow]")
        problem_acc_df_global, df_discrepancies_global = compare_results()

        # 10.Print result preview
        print("\n🔍 Preview of problem_acc_df_global:")
        print(problem_acc_df_global)
        print("\n🔍 df_discrepancies:")
        print(df_discrepancies_global)

        # Check GPU status
        check_gpu_status()

    except Exception as e:
        print(f"Running main failed: {e}")