# -*- coding: utf-8 -*-
"""5_deepseek-math-7b-instruct_84.38%.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19zFF1jdUaLE-kSr9DkPZMvItVYtMy5fg

# 5_deepseek-math-7b-instruct_84.38%
"""

# --------------------------------------------------
# 1. Install Dependencies and Environment Setup
# --------------------------------------------------
# Login to Huggingface
!huggingface-cli login
# Check GPU
!nvidia-smi

### 🚀 Step 1: Install Dependencies ###
!pip install -U transformers==4.51.3 torch==2.6.0+cu124 accelerate bitsandbytes datasets==3.5.0 peft==0.13.0 fsspec==2024.12.0 --extra-index-url https://download.pytorch.org/whl/cu124

### 🔧 Step 2: Set Environment Variables ###
import os
os.environ["WANDB_DISABLED"] = "true"  # Disable Weights & Biases logging
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"  # Dynamic memory allocation

### 🧠 Step 3: Import Libraries ###
import gc
import atexit
import contextlib
import logging
import torch
import subprocess
import time
import re
from contextlib import contextmanager
from rich.console import Console

# Transformer & PEFT
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    TrainerCallback,
    pipeline,
    DataCollatorForLanguageModeling
)
from peft import LoraConfig, get_peft_model, PeftModel, PeftConfig

# Datasets and Processing
from datasets import Dataset
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# Visualization and Utilities
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
from openpyxl.styles import Alignment
import pkg_resources

### 📝 Step 4: Logging Configuration ###
logging.basicConfig(format="%(asctime)s - %(levelname)s - %(message)s", level=logging.INFO)

### 📦 Step 5: Dependency Version Check ###
def check_dependencies():
    required_versions = {
        'transformers': '4.51.3',
        'torch': '2.6.0',
        'datasets': '3.5.0',
        'peft': '0.13.0',
        'openpyxl': '3.0.0'
    }
    print("🔍 Checking dependency versions...\n")
    for pkg, required in required_versions.items():
        try:
            installed = pkg_resources.get_distribution(pkg).version
            status = "✅ OK" if installed >= required else "⚠️ Too Low"
            print(f"{pkg}: Current version {installed} (Required >= {required}) {status}")
        except Exception as e:
            print(f"{pkg}: Not installed ❌")

check_dependencies()

### ⚙️ Step 6: Check GPU Status ###
print("\n🖥️ CUDA Available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("🧠 GPU Model:", torch.cuda.get_device_name(0))

torch.cuda.empty_cache()

### 🧼 Step 7: Resource Manager ###
@contextlib.contextmanager
def manage_resources(model=None):
    try:
        yield
    finally:
        if model is not None:
            del model
        gc.collect()
        torch.cuda.empty_cache()
        logging.info("Resources cleaned (manage_resources)")

@contextlib.contextmanager
def eval_mode(model):
    model.eval()
    try:
        yield
    finally:
        model.train()

### ⏱️ Step 7.5: Timer Decorator ###
def timer(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"⏱️ '{func.__name__}' execution time: {end - start:.2f} seconds")
        return result
    return wrapper

### 🧹 Step 8: Program Exit Cleanup ###
def cleanup():
    global model, trainer
    if 'model' in globals():
        del model
    if 'trainer' in globals():
        del trainer
    gc.collect()
    torch.cuda.empty_cache()
    print("✅ Program exited, resources cleaned (atexit)")

atexit.register(cleanup)

# ------------------------------------
# 3. Define Constants and Test Cases
# ------------------------------------
CRITERIA = [
    "Co-reference issues", "Grammatical errors", "Misspellings", "Incomplete sentences",
    "Unsolvable problems", "Unrealistic", "Unit issues", "Topic safety",
    "Not satisfying grade requirement", "Not satisfying section requirement",
    "Trivial", "Not a word problem"
]

TEST_CASES = [
    {"grade": "2", "question_type": "Addition", "problem": "How much is 5 plus 3?"},
    {"grade": "2", "question_type": "Addition", "problem": "There is 8 dogs in the park. 3 more dogs come to the park. How many dogs are there now?"},
    {"grade": "3", "question_type": "Addition", "problem": "John has 2 pencils that are 4 inches long each. If he buys another pencil that is 5 inches long, how gram long are all his pencils in total?"},
    {"grade": "1", "question_type": "Addition", "problem": "There are 3 red flowrs and 4 yello flowrs in a vase. How many flowrs are there in total?"},
    {"grade": "4", "question_type": "Subtraction", "problem": "There are 20 balloons in the box. Some of the balloons popped. If there are now 12 balloons left in the box, how many balloons popped?"},
    {"grade": "2", "question_type": "Addition", "problem": "There are 7 marbles in a bag and David puts. Now there are 10 in total. How many marbles did David add?"},
    {"grade": "5", "question_type": "Subtraction", "problem": "White is 19 years old and Black is 7 years younger than white. How old is Kalu?"},
    {"grade": "3", "question_type": "Subtraction", "problem": "If Jack has 27 apples and he gives 14 apples to his friend, how many apples does Jack have left?"},
    {"grade": "6", "question_type": "Multiplication", "problem": "A rectangular swimming pool has a length of 15 meters and a width of 6 meters. What is the area of the swimming pool in square meters?"},
    {"grade": "4", "question_type": "Addition", "problem": "A Murderer killed 5 persons last January. The murderer killed 4 persons in February. How many persons were killed at the end of the February month?"},
    {"grade": "6", "question_type": "Multiplication", "problem": "A rectangular garden has a length of 18 meters and a width of 8 meters. What is the area of the garden in square meters?"},
    {"grade": "3", "question_type": "Addition", "problem": "An man has a 14 number of eyes. If it blinks 5 of them, how many eyes are still open?"},
    {"grade": "2", "question_type": "Addition", "problem": "A bag contains 10 marbles. If you remove 2 marbles and add some more, how many marbles are in the bag now?"},
    {"grade": "2", "question_type": "Addition", "problem": "234+567"},
    {"grade": "3", "question_type": "Subtraction", "problem": "Sara killed catched 34 rats and killed 5 rats from them. how many rats are left?"},
    {"grade": "2", "question_type": "Division", "problem": "I have 35 apples and I share them equally with 7 friends. If each friend get 5 apples how many friends are there?"}
]

# -----------------------------------------
# 4. Define Prompt Templates and Examples
# -----------------------------------------
PROMPT_CONFIGS = {
    "zero_shot": {
        "template": '''
You are a math education evaluator. Your task is to evaluate the following math word problem using 12 binary criteria.
Analyze the problem carefully and assign 0 or 1 based on the criteria definitions.

⚠️ Output format rules:
- Output EXACTLY 12 lines, one for each criterion listed below.
- Each line MUST be formatted as: "- Criterion: 0" or "- Criterion: 1".
- Use ONLY the criterion names provided, in the exact order.
- DO NOT include explanations, numbered lists, descriptions, or any extra text.
- DO NOT skip, reorder, or add criteria.
- Non-compliance (e.g., adding explanations, using incorrect format) will invalidate the output.
- 0 indicates an error is detected; 1 indicates no error is detected.

Criteria (do NOT include in output):
1. Co-reference issues: Unclear pronouns/references (0 if present, 1 if absent).
2. Grammatical errors: Grammar mistakes (0 if present, 1 if absent).
3. Misspellings: Spelling errors (0 if present, 1 if absent).
4. Incomplete sentences: Sentences missing components (0 if present, 1 if absent).
5. Unsolvable problems: Missing information prevents solving (0 if true, 1 if solvable).
6. Unrealistic: Implausible scenario (0 if unrealistic, 1 if realistic).
7. Unit issues: Incorrect/inconsistent units (0 if present, 1 if absent).
8. Topic safety: Violent/inappropriate content (0 if present, 1 if safe).
9. Not satisfying grade requirement: Too hard/easy for grade (0 if true, 1 if appropriate).
10. Not satisfying section requirement: Mismatches section (0 if true, 1 if matches).
11. Trivial: Too simple for grade (0 if trivial, 1 if non-trivial).
12. Not a word problem: Equation only, no narrative (0 if true, 1 if narrative).

Example of CORRECT output:
- Co-reference issues: 1
- Grammatical errors: 1
- Misspellings: 1
- Incomplete sentences: 1
- Unsolvable problems: 1
- Unrealistic: 1
- Unit issues: 1
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 0
- Not a word problem: 1

Example of INCORRECT output (DO NOT DO THIS):
- 1. Co-reference issues: 1 (no pronouns)
- Grammatical errors: 1 (correct grammar)
- Missing criterion
Explanation: This is wrong.

### Evaluation Criteria
{criteria_list}

### Grade
{grade}

### Question Type
{question_type}

### Math Word Problem
{problem}
''',
        "example": None
    },
    "one_shot": {
        "template": '''
You are a math education evaluator. Your task is to evaluate the following math word problem using 12 binary criteria.
Analyze the problem carefully and assign 0 or 1 based on the criteria definitions.

⚠️ Output format rules:
- Output EXACTLY 12 lines, one for each criterion listed below.
- Each line MUST be formatted as: "- Criterion: 0" or "- Criterion: 1".
- Use ONLY the criterion names provided, in the exact order.
- DO NOT include explanations, numbered lists, descriptions, or any extra text.
- DO NOT skip, reorder, or add criteria.
- Non-compliance (e.g., adding explanations, using incorrect format) will invalidate the output.
- 0 indicates an error is detected; 1 indicates no error is detected.

Criteria (do NOT include in output):
1. Co-reference issues: Unclear pronouns/references (0 if present, 1 if absent).
2. Grammatical errors: Grammar mistakes (0 if present, 1 if absent).
3. Misspellings: Spelling errors (0 if present, 1 if absent).
4. Incomplete sentences: Sentences missing components (0 if present, 1 if absent).
5. Unsolvable problems: Missing information prevents solving (0 if true, 1 if solvable).
6. Unrealistic: Implausible scenario (0 if unrealistic, 1 if realistic).
7. Unit issues: Incorrect/inconsistent units (0 if present, 1 if absent).
8. Topic safety: Violent/inappropriate content (0 if present, 1 if safe).
9. Not satisfying grade requirement: Too hard/easy for grade (0 if true, 1 if appropriate).
10. Not satisfying section requirement: Mismatches section (0 if true, 1 if matches).
11. Trivial: Too simple for grade (0 if trivial, 1 if non-trivial).
12. Not a word problem: Equation only, no narrative (0 if true, 1 if narrative).

Example of CORRECT output:
- Co-reference issues: 1
- Grammatical errors: 1
- Misspellings: 1
- Incomplete sentences: 1
- Unsolvable problems: 1
- Unrealistic: 1
- Unit issues: 1
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 0
- Not a word problem: 1

Example of INCORRECT output (DO NOT DO THIS):
- 1. Co-reference issues: 1 (no pronouns)
- Grammatical errors: 1 (correct grammar)
- Missing criterion
Explanation: This is wrong.

### Evaluation Criteria
{criteria_list}

{example}

### Grade
{grade}

### Question Type
{question_type}

### Math Word Problem
{problem}

**Output exactly 12 lines in the format "- Criterion: [0 or 1]".**
''',
        "example": '''
### **Example Math Word Problem**
Tom has 5 apples. He gives some to his friend. How many does he have left?
Grade: 2
Question Type: Subtraction

### **Example Output**
- Co-reference issues: 1
- Grammatical errors: 1
- Misspellings: 1
- Incomplete sentences: 1
- Unsolvable problems: 0
- Unrealistic: 1
- Unit issues: 1
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 1
- Not a word problem: 1
'''
    },
    "three_shot": {
        "template": '''
You are an expert system designed to evaluate math word problems.
Analyze the given problem based on the criteria below. Output exactly 12 lines, each formatted as "- Criterion: [0 or 1]" (0 = Error present, 1 = No error).
Use the examples to guide your scoring, and carefully evaluate each criterion based on the problem's content, grade, and section.
Do not add extra text beyond the 12 lines.

⚠️ Output format rules:
- Output EXACTLY 12 lines, one for each criterion listed below.
- Each line MUST be formatted as: "- Criterion: 0" or "- Criterion: 1".
- Use ONLY the criterion names provided, in the exact order.
- DO NOT include explanations, numbered lists, descriptions, or any extra text.
- DO NOT skip, reorder, or add criteria.
- Non-compliance (e.g., adding explanations, using incorrect format) will invalidate the output.
- 0 indicates an error is detected; 1 indicates no error is detected.

Criteria (do NOT include in output):
1. Co-reference issues: Unclear pronouns/references (0 if present, 1 if absent).
2. Grammatical errors: Grammar mistakes (0 if present, 1 if absent).
3. Misspellings: Spelling errors (0 if present, 1 if absent).
4. Incomplete sentences: Sentences missing components (0 if present, 1 if absent).
5. Unsolvable problems: Missing information prevents solving (0 if true, 1 if solvable).
6. Unrealistic: Implausible scenario (0 if unrealistic, 1 if realistic).
7. Unit issues: Incorrect/inconsistent units (0 if present, 1 if absent).
8. Topic safety: Violent/inappropriate content (0 if present, 1 if safe).
9. Not satisfying grade requirement: Too hard/easy for grade (0 if true, 1 if appropriate).
10. Not satisfying section requirement: Mismatches section (0 if true, 1 if matches).
11. Trivial: Too simple for grade (0 if trivial, 1 if non-trivial).
12. Not a word problem: Equation only, no narrative (0 if true, 1 if narrative).

Example of CORRECT output:
- Co-reference issues: 1
- Grammatical errors: 1
- Misspellings: 1
- Incomplete sentences: 1
- Unsolvable problems: 1
- Unrealistic: 1
- Unit issues: 1
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 0
- Not a word problem: 1

Example of INCORRECT output (DO NOT DO THIS):
- 1. Co-reference issues: 1 (no pronouns)
- Grammatical errors: 1 (correct grammar)
- Missing criterion
Explanation: This is wrong.

### Evaluation Criteria
{criteria_list}

{example}

### Grade
{grade}

### Question Type
{question_type}

### Math Word Problem
{problem}

**Output exactly 12 lines in the format "- Criterion: [0 or 1]".**
''',
        "example": '''
### **Example Math Word Problem 1**
Lisa has 10 candies. She eats some. How many are left?
Grade: 2
Question Type: Subtraction

### **Example Output 1**
- Co-reference issues: 1
- Grammatical errors: 1
- Misspellings: 1
- Incomplete sentences: 1
- Unsolvable problems: 0
- Unrealistic: 1
- Unit issues: 1
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 1
- Not a word problem: 1

### **Example Math Word Problem 2**
A room is 5 meters long and 3 meters wide. What is its area in liters?
Grade: 5
Question Type: Multiplication

### **Example Output 2**
- Co-reference issues: 1
- Grammatical errors: 1
- Misspellings: 1
- Incomplete sentences: 1
- Unsolvable problems: 1
- Unrealistic: 0
- Unit issues: 0
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 0
- Not a word problem: 1

### **Example Math Word Problem 3**
6 + 9
Grade: 1
Question Type: Addition

### **Example Output 3**
- Co-reference issues: 1
- Grammatical errors: 1
- Misspellings: 1
- Incomplete sentences: 1
- Unsolvable problems: 1
- Unrealistic: 1
- Unit issues: 1
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 0
- Not a word problem: 0
'''
    }
}

# -------------------------------
# 5. Load Model and Tokenizer
# -------------------------------
def load_model_and_tokenizer(model_name="deepseek-ai/deepseek-math-7b-instruct"):
    def print_mem(label=""):
        print(f"{label}GPU Mem: Alloc {torch.cuda.memory_allocated()/1024**3:.2f}GB | "
              f"Reserv {torch.cuda.memory_reserved()/1024**3:.2f}GB")

    print_mem("Initial ")

    quant_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True
    )

    print_mem("Pre-load ")
    model = AutoModelForCausalLM.from_pretrained(
        model_name, quantization_config=quant_config, torch_dtype=torch.bfloat16,
        trust_remote_code=True, device_map="cuda:0", low_cpu_mem_usage=True
    )
    print_mem("Post-load ")

    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    print_mem("Final ")
    return model, tokenizer

# -------------------------------
# 6. Output Processing
# -------------------------------
def process_output(raw_output: str, problem: str, criteria: list = CRITERIA) -> str | None:
    """
    Processes raw model output to ensure it meets the specified format requirements.

    Args:
        raw_output: Raw model output string.
        problem: The math word problem for logging context.
        criteria: List of evaluation criteria.

    Returns:
        Formatted string with exactly 12 lines in the format "- Criterion: 0/1", or None if parsing fails.
    """
    output_map = {}
    found_binary = False
    for line in raw_output.strip().split('\n'):
        line = line.strip()
        if not line or ':' not in line:
            continue
        try:
            criterion_part, value_part = line.split(':', 1)
            criterion = criterion_part.replace('- ', '').strip()
            if criterion.startswith(tuple(str(i) + '.' for i in range(1, 13))):
                criterion = criterion.split('.', 1)[1].strip()
            value = value_part.strip().split()[0] if value_part.strip() else None
            if criterion in criteria and value in ('0', '1', 'True', 'False', '1.0', '0.0'):
                output_map[criterion] = '1' if value in ('1', 'True', '1.0') else '0'
                found_binary = True
        except (ValueError, IndexError) as e:
            logging.debug(f"Skipping malformed line: {line}, error: {e}")
            continue

    if not found_binary:
        logging.warning(f"No valid binary values found in output for problem: {problem}")
        return None

    if len(output_map) != len(criteria):
        logging.warning(f"Incomplete output: {len(output_map)} criteria found, expected {len(criteria)} for problem: {problem}")

    final_output = []
    for criterion in criteria:
        value = output_map.get(criterion, 'N/A')  # Default to N/A for missing criteria
        final_output.append(f"- {criterion}: {value}")
    return '\n'.join(final_output)

# -------------------------------
# 7. Run Prompting
# -------------------------------
def run_prompting(model, tokenizer, shot_type, test_cases=TEST_CASES):
    pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)
    criteria_list = "\n".join([f"{i+1}. {c}: 0 if {d}" for i, (c, d) in enumerate([
        ("Co-reference issues", "pronouns/references are unclear (e.g., 'he' without context)"),
        ("Grammatical errors", "there are grammar mistakes"),
        ("Misspellings", "there are spelling errors"),
        ("Incomplete sentences", "a sentence is incomplete"),
        ("Unsolvable problems", "missing info prevents solving (e.g., no quantity given)"),
        ("Unrealistic", "the scenario is implausible (e.g., a man with 14 eyes)"),
        ("Unit issues", "units are incorrect/inconsistent (e.g., length in grams)"),
        ("Topic safety", "violent/inappropriate (e.g., murder references)"),
        ("Not satisfying grade requirement", "too hard/easy for the grade"),
        ("Not satisfying section requirement", "doesn’t match the section (e.g., addition vs subtraction)"),
        ("Trivial", "too simple for the grade"),
        ("Not a word problem", "just an equation, no narrative")
    ])])

    results = []
    config = PROMPT_CONFIGS[shot_type]
    for case in test_cases:
        prompt = config["template"].format(
            criteria_list=criteria_list,
            example=config["example"] or "",
            grade=case["grade"],
            question_type=case["question_type"],
            problem=case["problem"]
        )
        output = pipe(
            prompt,
            max_new_tokens=250,
            do_sample=shot_type != "zero_shot",
            temperature=0.2 if shot_type == "zero_shot" else 0.7,
            top_k=50,
            top_p=0.95,
            return_full_text=False
        )[0]['generated_text']
        formatted_output = process_output(output, case["problem"])
        if formatted_output is None:
            logging.warning(f"Using default output for problem: {case['problem']}")
            formatted_output = '\n'.join(f"- {criterion}: N/A" for criterion in CRITERIA)
        results.append({
            "problem": case["problem"],
            "grade": case["grade"],
            "question_type": case["question_type"],
            "output": formatted_output
        })
        print(f"Problem: {case['problem']}\nGrade: {case['grade']}\nQuestion Type: {case['question_type']}\nModel Output:\n{formatted_output}\n{'-'*50}")
    return results

# -------------------------------
# 8. Data Preparation
# -------------------------------
def prepare_data(df_final, random_seed=42):
    df_train, temp_data = train_test_split(
        df_final, test_size=0.2, stratify=df_final["Grade"], random_state=random_seed
    )
    df_val, df_test = train_test_split(
        temp_data, test_size=0.5, stratify=temp_data["Grade"], random_state=random_seed
    )
    return Dataset.from_pandas(df_train), Dataset.from_pandas(df_val), Dataset.from_pandas(df_test)

def format_data(examples):
    prompts = []
    labels = []
    for i in range(len(examples["Problem"])):
        prompt = (
            f"Analyze this math problem and output a list of 0s and 1s for these error types: {', '.join(CRITERIA)}.\n"
            f"Problem: {examples['Problem'][i]}\n"
            f"Grade: {examples['Grade'][i]}\n"
            f"Section: {examples['Section'][i]}\n"
            "Output:\n"
        )
        label = " ".join(str(examples.get(col, 0)[i]) for col in CRITERIA)
        prompts.append(prompt)
        labels.append(label)
    return {"prompt": prompts, "label": labels}

def tokenize_function(examples, tokenizer, max_length=256):
    full_texts = [p + l for p, l in zip(examples["prompt"], examples["label"])]
    tokenized = tokenizer(
        full_texts, padding="max_length", truncation=True, max_length=max_length,
        return_tensors="pt", padding_side="right"
    )
    input_ids = tokenized["input_ids"]
    attention_mask = tokenized["attention_mask"]
    prompt_tokenized = tokenizer(
        examples["prompt"], padding="max_length", truncation=True,
        max_length=max_length - 24, return_tensors="pt", padding_side="right"
    )
    labels = torch.full_like(input_ids, -100, dtype=torch.long)
    for i in range(len(examples["prompt"])):
        prompt_len = (prompt_tokenized["attention_mask"][i] == 1).sum().item()
        label_tokens = [int(x) for x in examples["label"][i].strip().split()]
        label_tensor = torch.tensor(label_tokens, dtype=torch.long)
        if prompt_len + len(label_tokens) <= max_length:
            labels[i, prompt_len:prompt_len + len(label_tokens)] = label_tensor
    return {
        "input_ids": input_ids.tolist(),
        "attention_mask": attention_mask.tolist(),
        "labels": labels.tolist()
    }

# -------------------------------
# 9. Model Training
# -------------------------------
def train_model(model, tokenizer, train_dataset, val_dataset):
    lora_config = LoraConfig(
        r=8, lora_alpha=32, target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        lora_dropout=0.05, bias="none", task_type="CAUSAL_LM"
    )
    model = get_peft_model(model, lora_config)
    model.config.use_cache = False
    model.train()
    for name, param in model.named_parameters():
        param.requires_grad_("lora" in name)

    data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
    training_args = TrainingArguments(
        output_dir="./results",
        num_train_epochs=2,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        optim="adamw_torch",
        learning_rate=5e-5,
        warmup_steps=100,
        bf16=True,
        save_steps=500,
        logging_steps=10,
        eval_strategy="steps",
        eval_steps=100,
        save_total_limit=5,
        load_best_model_at_end=True,
        metric_for_best_model="loss",
        report_to="none",
    )

    trainer = Trainer(
        model=model, args=training_args, train_dataset=train_dataset,
        eval_dataset=val_dataset, data_collator=data_collator
    )
    try:
        trainer.train()
        save_path = "./fine_tuned_deepseek-math-7b-instruct"
        trainer.save_model(save_path)
        tokenizer.save_pretrained(save_path)
        # Verify saved files
        if os.path.exists(save_path):
            print(f"Model saved successfully. Files in {save_path}: {os.listdir(save_path)}")
        else:
            print(f"Error: Model directory {save_path} was not created.")
    except Exception as e:
        print(f"Error during training or saving: {e}")
        raise

    # Visualize training
    log_history = trainer.state.log_history
    train_loss = [log['loss'] for log in log_history if 'loss' in log]
    val_loss = [log['eval_loss'] for log in log_history if 'eval_loss' in log]
    steps = range(100, 100 + 100 * len(val_loss), 100)
    plt.plot(steps, train_loss[:len(val_loss)], label='Training Loss')
    plt.plot(steps, val_loss, label='Validation Loss')
    plt.xlabel('Step')
    plt.ylabel('Loss')
    plt.legend()
    plt.show()

# -------------------------------
# 10. Test Fine-Tuned Model
# -------------------------------
def test_fine_tuned_model(adapter_path="fine_tuned_deepseek-math-7b-instruct"):
    import os
    # Convert to absolute path and validate
    adapter_path = os.path.abspath(adapter_path)
    if not os.path.exists(adapter_path):
        raise FileNotFoundError(f"Directory '{adapter_path}' does not exist.")
    if not os.path.isfile(os.path.join(adapter_path, "adapter_config.json")):
        raise FileNotFoundError(f"'adapter_config.json' not found in '{adapter_path}'.")

    peft_config = PeftConfig.from_pretrained(adapter_path)
    base_model_name = peft_config.base_model_name_or_path or "deepseek-ai/deepseek-math-7b-instruct"
    model = AutoModelForCausalLM.from_pretrained(
        base_model_name, torch_dtype=torch.bfloat16, trust_remote_code=True,
        load_in_4bit=True, device_map="cuda:0"
    )
    model = PeftModel.from_pretrained(model, adapter_path)
    tokenizer = AutoTokenizer.from_pretrained(adapter_path, trust_remote_code=True)
    model.eval()

    prompt_template = '''
You are a math education evaluator. Your task is to evaluate the following math word problem using 12 binary criteria.
Analyze the problem carefully and assign 0 or 1 based on the criteria definitions.

⚠️ Output format rules:
- Output EXACTLY 12 lines, one for each criterion listed below.
- Each line MUST be formatted as: "- Criterion: 0" or "- Criterion: 1".
- Use ONLY the criterion names provided, in the exact order.
- DO NOT include explanations, numbered lists, descriptions, or any extra text.
- DO NOT skip, reorder, or add criteria.
- Non-compliance (e.g., adding explanations, using incorrect format) will invalidate the output.
- 0 indicates an error is detected; 1 indicates no error is detected.

Criteria (do NOT include in output):
1. Co-reference issues: Unclear pronouns/references (0 if present, 1 if absent).
2. Grammatical errors: Grammar mistakes (0 if present, 1 if absent).
3. Misspellings: Spelling errors (0 if present, 1 if absent).
4. Incomplete sentences: Sentences missing components (0 if present, 1 if absent).
5. Unsolvable problems: Missing information prevents solving (0 if true, 1 if solvable).
6. Unrealistic: Implausible scenario (0 if unrealistic, 1 if realistic).
7. Unit issues: Incorrect/inconsistent units (0 if present, 1 if absent).
8. Topic safety: Violent/inappropriate content (0 if present, 1 if safe).
9. Not satisfying grade requirement: Too hard/easy for grade (0 if true, 1 if appropriate).
10. Not satisfying section requirement: Mismatches section (0 if true, 1 if matches).
11. Trivial: Too simple for grade (0 if trivial, 1 if non-trivial).
12. Not a word problem: Equation only, no narrative (0 if true, 1 if narrative).

Example of CORRECT output:
- Co-reference issues: 1
- Grammatical errors: 1
- Misspellings: 1
- Incomplete sentences: 1
- Unsolvable problems: 1
- Unrealistic: 1
- Unit issues: 1
- Topic safety: 1
- Not satisfying grade requirement: 1
- Not satisfying section requirement: 1
- Trivial: 0
- Not a word problem: 1

Example of INCORRECT output (DO NOT DO THIS):
- 1. Co-reference issues: 1 (no pronouns)
- Grammatical errors: 1 (correct grammar)
- Missing criterion
Explanation: This is wrong.

Criteria:
{criteria_list}

Problem: "{problem}"
'''
    criteria_list = "\n".join([f"{i+1}. {c}" for i, c in enumerate(CRITERIA)])

    def generate_answer(prompt):
        inputs = tokenizer(prompt, return_tensors="pt").to("cuda:0")
        with torch.no_grad():
            outputs = model.generate(
                **inputs, max_new_tokens=200, temperature=0.2, top_p=0.9,
                do_sample=True, pad_token_id=tokenizer.eos_token_id
            )
        return tokenizer.decode(outputs[0][len(inputs["input_ids"][0]):], skip_special_tokens=True).strip()

    table_data = []
    for case in TEST_CASES:
        prompt = prompt_template.format(criteria_list=criteria_list, problem=case["problem"])
        raw_output = generate_answer(prompt)
        formatted_output = process_output(raw_output, case["problem"])
        if formatted_output is None:
            logging.warning(f"Using default output for problem: {case['problem']}")
            formatted_output = '\n'.join(f"- {criterion}: N/A" for criterion in CRITERIA)
        print(f"Problem: {case['problem']}\nModel Output:\n{formatted_output}\n{'-'*50}")
        scores = {line.split(': ')[0].replace('- ', '').strip(): line.split(': ')[1].strip()
                  for line in formatted_output.split('\n') if ': ' in line}
        row = {"Problem": case["problem"]}
        for criterion in CRITERIA:
            row[criterion] = scores.get(criterion, "1")
        table_data.append(row)

    df_evaluation = pd.DataFrame(table_data, columns=["Problem"] + CRITERIA)
    df_evaluation.to_excel("test_results.xlsx", index=False, engine='openpyxl')
    print("Results saved to test_results.xlsx")
    return df_evaluation

# ----------------------------------
# 11. Compare with Human Evaluation
# ----------------------------------
def compare_evaluations(df_fine_tuned, human_file="/content/MWP evaluation sheet.xlsx"):
    df_human = pd.read_excel(human_file)

    # Diagnostic: Check shapes and problems
    print(f"df_fine_tuned shape: {df_fine_tuned.shape}")
    print(f"df_fine_tuned Problems:\n{df_fine_tuned['Problem'].tolist()}")
    print(f"df_human shape: {df_human.shape}")
    print(f"df_human Problems:\n{df_human['Problem'].tolist()}")
    print(f"df_human columns:\n{df_human.columns.tolist()}")
    missing_criteria = [c for c in CRITERIA if c not in df_human.columns]
    print(f"Missing criteria in df_human:\n{missing_criteria}")

    # Normalize Problem column
    df_human['Problem'] = df_human['Problem'].str.strip().str.lower()
    df_fine_tuned['Problem'] = df_fine_tuned['Problem'].str.strip().str.lower()

    # Drop rows with missing Problem values
    df_human = df_human.dropna(subset=['Problem'])
    df_fine_tuned = df_fine_tuned.dropna(subset=['Problem'])

    # Merge DataFrames
    df_merged = pd.merge(df_human, df_fine_tuned, on='Problem', how='inner', suffixes=('_human', '_ft'))

    # Diagnostic: Check merge result
    print(f"df_merged shape: {df_merged.shape}")
    print(f"df_merged Problems:\n{df_merged['Problem'].tolist()}")
    missing_problems = set(df_fine_tuned['Problem']) - set(df_merged['Problem'])
    print(f"Problems missing in df_merged:\n{missing_problems}")

    # Check available columns
    available_columns = [col for col in CRITERIA if f"{col}_human" in df_merged.columns and f"{col}_ft" in df_merged.columns]
    print(f"Available columns for comparison:\n{available_columns}")

    problem_accuracy = []
    total_correct = total_comparisons = 0
    for _, row in df_merged.iterrows():
        correct_count = 0
        for col in available_columns:
            human_val = row[f"{col}_human"]
            ft_val = row[f"{col}_ft"]
            if pd.isna(human_val) or pd.isna(ft_val):
                continue
            try:
                human_val = float(human_val) if str(human_val).replace('.', '').isdigit() else str(human_val)
                ft_val = float(ft_val) if str(ft_val).replace('.', '').isdigit() else str(ft_val)
            except (ValueError, TypeError):
                human_val = str(human_val)
                ft_val = str(ft_val)
            if human_val == ft_val:
                correct_count += 1
        accuracy = (correct_count / len(available_columns)) * 100 if available_columns else 0
        problem_accuracy.append({
            'Problem': row['Problem'],
            'Accuracy': accuracy,
            'Correct_Count': correct_count,
            'Total_Columns': len(available_columns)
        })
        total_correct += correct_count
        total_comparisons += len(available_columns)

    overall_accuracy = (total_correct / total_comparisons) * 100 if total_comparisons > 0 else 0
    problem_acc_df = pd.DataFrame(problem_accuracy)
    overall_row = pd.DataFrame([{
        'Problem': 'Overall Accuracy',
        'Total_Columns': total_comparisons,
        'Correct_Count': total_correct,
        'Accuracy': overall_accuracy
    }])
    problem_acc_df = pd.concat([problem_acc_df, overall_row], ignore_index=True)

    with pd.ExcelWriter("accuracy_results.xlsx", engine='openpyxl') as writer:
        problem_acc_df.to_excel(writer, sheet_name='Accuracy', index=False)
        worksheet = writer.sheets['Accuracy']
        for cell in worksheet['A'][1:]:
            cell.alignment = Alignment(horizontal='left')
        worksheet.column_dimensions['A'].width = 50
        worksheet.column_dimensions['B'].width = 15
        worksheet.column_dimensions['C'].width = 15
        worksheet.column_dimensions['D'].width = 15

    print(f"Total Problems: {len(df_merged)}\nOverall Accuracy: {overall_accuracy:.2f}%")
    print("\nAccuracy by Problem:")
    print(problem_acc_df)

    return problem_acc_df

# -------------------------------
# 12. Main Execution
# -------------------------------
def main():
    # Initialize memory monitoring
    def print_mem(label=""):
        print(f"{label}GPU Mem: Alloc {torch.cuda.memory_allocated()/1024**3:.2f}GB | "
              f"Reserv {torch.cuda.memory_reserved()/1024**3:.2f}GB")

    # 1. Initial cleanup and memory baseline
    torch.cuda.empty_cache()
    print("\n\033[92m=== Initial Memory Status ===\033[0m")
    print_mem("Start: ")

    # 2. Load model and tokenizer
    print("\n\033[92m=== Loading Model ===\033[0m")
    model, tokenizer = load_model_and_tokenizer()

    # 3. Prompt testing phase
    print("\n\033[92m=== Prompt Testing Phase ===\033[0m")
    for shot_type in ["zero_shot", "one_shot", "three_shot"]:
        torch.cuda.empty_cache()
        print(f"\n\033[93m=============== {shot_type.replace('_', ' ').title()} ===============\033[0m")
        print_mem(f"Before {shot_type}: ")
        run_prompting(model, tokenizer, shot_type)
        print_mem(f"After {shot_type}: ")

    # 4. Data processing phase
    print("\n\033[92m=== Data Processing ===\033[0m")
    df_final = pd.read_csv('/content/df_final.csv', encoding='ISO-8859-1')
    train_dataset, val_dataset, test_dataset = prepare_data(df_final)
    print_mem("After data loading: ")

    # 5. Tokenization
    print("\n\033[92m=== Tokenization ===\033[0m")
    formatted_train_ds = train_dataset.map(format_data, batched=True, remove_columns=train_dataset.column_names)
    tokenized_train = formatted_train_ds.map(lambda x: tokenize_function(x, tokenizer), batched=True, remove_columns=["prompt", "label"])
    formatted_val_ds = val_dataset.map(format_data, batched=True, remove_columns=val_dataset.column_names)
    tokenized_val = formatted_val_ds.map(lambda x: tokenize_function(x, tokenizer), batched=True, remove_columns=["prompt", "label"])
    print_mem("After tokenization: ")

    # 6. Training phase
    print("\n\033[92m=== Training Phase ===\033[0m")
    print_mem("Pre-train: ")
    train_model(model, tokenizer, tokenized_train, tokenized_val)
    print_mem("Post-train: ")

    # 7. Testing phase
    print("\n\033[92m=== Testing Phase ===\033[0m")
    df_evaluation = test_fine_tuned_model()
    compare_evaluations(df_evaluation)

    # Final memory status
    print("\n\033[92m=== Final Memory Status ===\033[0m")
    print_mem("Final: ")

if __name__ == "__main__":
    main()